/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks/{taskId}/outbound-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["callOutboundWorker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/inbound-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["callInboundWorkers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety/events/{eventId}/notify-nearby-workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["notifyNearbyWorkers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety/events/ai-cctv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAiCctvEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOutboundTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbound/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recommend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/wifi-signals/dummy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createDummySignals"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createWorkerAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["complete"];
        trace?: never;
    };
    "/api/task-assignments/{assignmentId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["reject"];
        trace?: never;
    };
    "/api/task-assignments/{assignmentId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["accept"];
        trace?: never;
    };
    "/api/safety/events/{eventId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["resolve"];
        trace?: never;
    };
    "/api/safety/events/{eventId}/assign-worker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["assignWorker"];
        trace?: never;
    };
    "/api/workers/{workerId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/my-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventories/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLayout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attendance/workers/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkerStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TaskCallResponse: {
            /** Format: int64 */
            taskId?: number;
            /** Format: int64 */
            assignmentId?: number;
            alarmKey?: string;
            /** Format: int64 */
            workerId?: number;
            employeeNo?: string;
            workerName?: string;
            assignmentStatus?: string;
            nearestApCode?: string;
            /** Format: int32 */
            rssi?: number;
            /** Format: int64 */
            locationId?: number;
            locationCode?: string;
            /** Format: int32 */
            locationPosX?: number;
            /** Format: int32 */
            locationPosY?: number;
            /** Format: date-time */
            calledAt?: string;
        };
        NotifyNearbyWorkersRequest: {
            /** Format: int32 */
            maxWorkers?: number;
        };
        NotifiedWorkerResponse: {
            /** Format: int64 */
            workerId?: number;
            employeeNo?: string;
            workerName?: string;
            /** Format: int32 */
            rssi?: number;
            alarmKey?: string;
        };
        NotifyNearbyWorkersResponse: {
            /** Format: int64 */
            eventId?: number;
            /** Format: int64 */
            storageLocationId?: number;
            storageLocationCode?: string;
            nearestAccessPointCode?: string;
            /** Format: int32 */
            notifiedCount?: number;
            notifiedWorkers?: components["schemas"]["NotifiedWorkerResponse"][];
            /** Format: date-time */
            notifiedAt?: string;
        };
        AiCctvSafetyDetectionRequest: {
            label?: string;
            confidence?: number;
        };
        AiCctvSafetyEventData: {
            sourceType?: string;
            eventType?: string;
            confidenceScore?: number;
            helmetWorn?: boolean;
            vestWorn?: boolean;
            annotatedImageUrl?: string;
            detections?: components["schemas"]["AiCctvSafetyDetectionRequest"][];
            /** Format: int32 */
            count?: number;
            cameraCode?: string;
            /** Format: int64 */
            storageLocationId?: number;
            storageLocationCode?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        AiCctvSafetyEventRequest: {
            success?: boolean;
            data?: components["schemas"]["AiCctvSafetyEventData"];
            message?: string;
            sourceType?: string;
            eventType?: string;
            confidenceScore?: number;
            helmetWorn?: boolean;
            vestWorn?: boolean;
            annotatedImageUrl?: string;
            detections?: components["schemas"]["AiCctvSafetyDetectionRequest"][];
            /** Format: int32 */
            count?: number;
            cameraCode?: string;
            /** Format: int64 */
            storageLocationId?: number;
            storageLocationCode?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        AiCctvSafetyEventResponse: {
            /** Format: int64 */
            id?: number;
            status?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        OutboundRequest: {
            /** Format: int64 */
            inventoryId?: number;
            /** Format: int32 */
            quantity?: number;
        };
        OutboundResponse: {
            /** Format: int64 */
            taskId?: number;
            taskStatus?: string;
            /** Format: int64 */
            inventoryId?: number;
            /** Format: int64 */
            itemId?: number;
            itemName?: string;
            /** Format: int32 */
            quantity?: number;
            /** Format: int64 */
            sourceLocationId?: number;
            sourceLocationCode?: string;
            sourceLocationName?: string;
            /** @enum {string} */
            areaCode?: "A" | "B" | "C";
            /** Format: int32 */
            sourceLocationPosX?: number;
            /** Format: int32 */
            sourceLocationPosY?: number;
            /** Format: int32 */
            availableQuantity?: number;
        };
        InboundRecommendRequest: {
            itemName?: string;
            /** Format: int32 */
            quantity?: number;
        };
        InboundRecommendResponse: {
            /** Format: int64 */
            taskId?: number;
            taskStatus?: string;
            /** Format: int64 */
            itemId?: number;
            sku?: string;
            itemName?: string;
            /** Format: int32 */
            quantity?: number;
            /** @enum {string} */
            recommendedGrade?: "A" | "B" | "C";
            /** Format: int64 */
            locationId?: number;
            locationCode?: string;
            locationName?: string;
            /** @enum {string} */
            areaCode?: "A" | "B" | "C";
            dangerArea?: boolean;
            /** Format: int32 */
            posX?: number;
            /** Format: int32 */
            posY?: number;
            /** Format: int32 */
            capacity?: number;
        };
        CreateDummyWifiSignalsRequest: {
            /** Format: int32 */
            ttlSeconds?: number;
            signals?: components["schemas"]["DummyWorkerWifiSignalRequest"][];
        };
        DummyWorkerWifiSignalRequest: {
            /** Format: int64 */
            workerId?: number;
            employeeNo?: string;
            rssiByApCode?: {
                [key: string]: number;
            };
        };
        CreateDummyWifiSignalsResponse: {
            /** Format: int32 */
            workerCount?: number;
            /** Format: int32 */
            accessPointCount?: number;
            /** Format: int32 */
            ttlSeconds?: number;
            signals?: components["schemas"]["DummyWorkerWifiSignalResponse"][];
        };
        DummyWorkerWifiSignalResponse: {
            /** Format: int64 */
            workerId?: number;
            employeeNo?: string;
            redisKey?: string;
            strongestApCode?: string;
            rssiByApCode?: {
                [key: string]: number;
            };
        };
        CreateWorkerAccountRequest: {
            loginId?: string;
            password?: string;
            name?: string;
            employeeNo?: string;
        };
        CreateWorkerAccountResponse: {
            /** Format: int64 */
            userId?: number;
            loginId?: string;
            name?: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER";
            /** Format: int64 */
            workerId?: number;
            employeeNo?: string;
            workerStatus?: string;
        };
        LoginRequest: {
            username?: string;
            password?: string;
        };
        AuthUserResponse: {
            /** Format: int64 */
            id?: number;
            username?: string;
            name?: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER";
        };
        LoginResponse: {
            accessToken?: string;
            user?: components["schemas"]["AuthUserResponse"];
        };
        TaskActionResponse: {
            /** Format: int64 */
            taskId?: number;
            /** Format: int64 */
            assignmentId?: number;
            /** Format: int64 */
            workerId?: number;
            taskStatus?: string;
            assignmentStatus?: string;
            /** Format: date-time */
            respondedAt?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        ResolveSafetyEventRequest: {
            /** Format: int64 */
            resolvedByUserId?: number;
            resolutionMemo?: string;
        };
        SafetyEventActionResponse: {
            /** Format: int64 */
            eventId?: number;
            status?: string;
            /** Format: int64 */
            workerId?: number;
            workerEmployeeNo?: string;
            workerName?: string;
            /** Format: date-time */
            assignedAt?: string;
            /** Format: date-time */
            resolvedAt?: string;
        };
        AssignSafetyEventWorkerRequest: {
            /** Format: int64 */
            workerId?: number;
            employeeNo?: string;
            /** Format: int64 */
            assignedByUserId?: number;
        };
        WorkerAssignmentResponse: {
            /** Format: int64 */
            assignmentId?: number;
            /** Format: int64 */
            taskId?: number;
            status?: string;
            taskType?: string;
            /** Format: int64 */
            itemId?: number;
            itemName?: string;
            /** Format: int32 */
            quantity?: number;
            /** Format: int64 */
            sourceLocationId?: number;
            sourceLocationCode?: string;
            /** Format: int64 */
            targetLocationId?: number;
            targetLocationCode?: string;
            /** Format: date-time */
            calledAt?: string;
        };
        SafetyEventListResponse: {
            /** Format: int64 */
            totalCount?: number;
            /** Format: int64 */
            activeCount?: number;
            /** Format: int64 */
            resolvedCount?: number;
            events?: components["schemas"]["SafetyEventSummaryResponse"][];
        };
        SafetyEventSummaryResponse: {
            /** Format: int64 */
            eventId?: number;
            eventType?: string;
            eventTypeLabel?: string;
            status?: string;
            statusLabel?: string;
            /** Format: int64 */
            storageLocationId?: number;
            storageLocationCode?: string;
            storageLocationName?: string;
            captureUrl?: string;
            /** Format: int64 */
            workerId?: number;
            workerEmployeeNo?: string;
            workerName?: string;
            /** Format: date-time */
            occurredAt?: string;
            /** Format: date-time */
            resolvedAt?: string;
        };
        SafetyEventDetailResponse: {
            /** Format: int64 */
            eventId?: number;
            eventType?: string;
            eventTypeLabel?: string;
            sourceType?: string;
            status?: string;
            statusLabel?: string;
            captureUrl?: string;
            confidenceScore?: number;
            helmetWorn?: boolean;
            vestWorn?: boolean;
            shoesWorn?: boolean;
            /** Format: int64 */
            storageLocationId?: number;
            storageLocationCode?: string;
            storageLocationName?: string;
            /** Format: int32 */
            storagePosX?: number;
            /** Format: int32 */
            storagePosY?: number;
            /** Format: int64 */
            cameraId?: number;
            cameraCode?: string;
            /** Format: int64 */
            workerId?: number;
            workerEmployeeNo?: string;
            workerName?: string;
            /** Format: int64 */
            assignedByUserId?: number;
            assignedByName?: string;
            /** Format: date-time */
            assignedAt?: string;
            /** Format: int64 */
            resolvedByUserId?: number;
            resolvedByName?: string;
            resolutionMemo?: string;
            /** Format: date-time */
            occurredAt?: string;
            /** Format: date-time */
            resolvedAt?: string;
        };
        InventorySearchResponse: {
            keyword?: string;
            /** Format: int32 */
            resultCount?: number;
            /** Format: int32 */
            totalInventoryCount?: number;
            /** Format: int32 */
            totalQuantity?: number;
            selectedResult?: components["schemas"]["InventorySearchResultResponse"];
            searchResults?: components["schemas"]["InventorySearchResultResponse"][];
            inventoryItems?: components["schemas"]["InventorySearchResultResponse"][];
            slots?: components["schemas"]["InventorySlotResponse"][];
        };
        InventorySearchResultResponse: {
            /** Format: int64 */
            inventoryId?: number;
            /** Format: int64 */
            itemId?: number;
            sku?: string;
            itemName?: string;
            category?: string;
            /** Format: int32 */
            quantity?: number;
            /** Format: int64 */
            locationId?: number;
            locationCode?: string;
            locationName?: string;
            /** @enum {string} */
            areaCode?: "A" | "B" | "C";
            /** @enum {string} */
            locationGrade?: "A" | "B" | "C";
            dangerArea?: boolean;
            /** Format: int32 */
            posX?: number;
            /** Format: int32 */
            posY?: number;
            /** Format: int32 */
            rowIndex?: number;
            /** Format: int32 */
            columnIndex?: number;
            locationLabel?: string;
            /** Format: int32 */
            capacity?: number;
            /** Format: date-time */
            lastMovedAt?: string;
        };
        InventorySlotResponse: {
            /** Format: int64 */
            locationId?: number;
            locationCode?: string;
            locationName?: string;
            /** @enum {string} */
            areaCode?: "A" | "B" | "C";
            /** @enum {string} */
            locationGrade?: "A" | "B" | "C";
            dangerArea?: boolean;
            /** Format: int32 */
            posX?: number;
            /** Format: int32 */
            posY?: number;
            /** Format: int32 */
            rowIndex?: number;
            /** Format: int32 */
            columnIndex?: number;
            /** Format: int32 */
            capacity?: number;
            /** Format: int32 */
            storedQuantity?: number;
            occupied?: boolean;
            matched?: boolean;
            itemNames?: string[];
        };
        InventoryLayoutResponse: {
            /** Format: int32 */
            totalInventoryCount?: number;
            /** Format: int32 */
            totalQuantity?: number;
            inventoryItems?: components["schemas"]["InventorySearchResultResponse"][];
            slots?: components["schemas"]["InventorySlotResponse"][];
        };
        DashboardInboundItemResponse: {
            /** Format: int64 */
            taskId?: number;
            /** Format: int64 */
            itemId?: number;
            itemName?: string;
            /** Format: int32 */
            quantity?: number;
            targetLocationCode?: string;
            /** Format: date-time */
            requestedAt?: string;
        };
        DashboardSafetyItemResponse: {
            /** Format: int64 */
            safetyEventId?: number;
            eventType?: string;
            locationCode?: string;
            workerName?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        DashboardSummaryResponse: {
            /** Format: int64 */
            inProgressTaskCount?: number;
            /** Format: int64 */
            availableWorkerCount?: number;
            /** Format: int64 */
            safetyViolationCount?: number;
            /** Format: int64 */
            pendingInboundCount?: number;
            inProgressTasks?: components["schemas"]["DashboardTaskItemResponse"][];
            availableWorkers?: components["schemas"]["DashboardWorkerItemResponse"][];
            safetyViolations?: components["schemas"]["DashboardSafetyItemResponse"][];
            pendingInbounds?: components["schemas"]["DashboardInboundItemResponse"][];
        };
        DashboardTaskItemResponse: {
            /** Format: int64 */
            taskId?: number;
            itemName?: string;
            /** Format: int32 */
            quantity?: number;
            status?: string;
        };
        DashboardWorkerItemResponse: {
            /** Format: int64 */
            workerId?: number;
            employeeNo?: string;
            name?: string;
            status?: string;
        };
        WorkerAttendanceStatsResponse: {
            /** Format: int64 */
            workerId?: number;
            name?: string;
            status?: string;
            /** Format: int64 */
            callAccepted?: number;
            /** Format: int64 */
            tasksHandled?: number;
            /** Format: int64 */
            violations?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    callOutboundWorker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskCallResponse"];
                };
            };
        };
    };
    callInboundWorkers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskCallResponse"][];
                };
            };
        };
    };
    notifyNearbyWorkers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NotifyNearbyWorkersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotifyNearbyWorkersResponse"];
                };
            };
        };
    };
    createAiCctvEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiCctvSafetyEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AiCctvSafetyEventResponse"];
                };
            };
        };
    };
    createOutboundTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutboundRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OutboundResponse"];
                };
            };
        };
    };
    recommend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboundRecommendRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InboundRecommendResponse"];
                };
            };
        };
    };
    createDummySignals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateDummyWifiSignalsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateDummyWifiSignalsResponse"];
                };
            };
        };
    };
    createWorkerAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkerAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateWorkerAccountResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskActionResponse"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskActionResponse"];
                };
            };
        };
    };
    accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskActionResponse"];
                };
            };
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ResolveSafetyEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SafetyEventActionResponse"];
                };
            };
        };
    };
    assignWorker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignSafetyEventWorkerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SafetyEventActionResponse"];
                };
            };
        };
    };
    getAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkerAssignmentResponse"][];
                };
            };
        };
    };
    getMyCalls: {
        parameters: {
            query?: {
                workerId?: number;
            };
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkerAssignmentResponse"][];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                eventType?: string;
                status?: string;
                storageLocationCode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SafetyEventListResponse"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SafetyEventDetailResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                itemName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InventorySearchResponse"];
                };
            };
        };
    };
    getLayout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InventoryLayoutResponse"];
                };
            };
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DashboardSummaryResponse"];
                };
            };
        };
    };
    getWorkerStats: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkerAttendanceStatsResponse"][];
                };
            };
        };
    };
}
