/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createWorkerAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateWorkerAccountRequest: {
            loginId?: string;
            password?: string;
            name?: string;
            employeeNo?: string;
        };
        CreateWorkerAccountResponse: {
            /** Format: int64 */
            userId?: number;
            loginId?: string;
            name?: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER";
            /** Format: int64 */
            workerId?: number;
            employeeNo?: string;
            workerStatus?: string;
        };
        LoginRequest: {
            username?: string;
            password?: string;
        };
        AuthUserResponse: {
            /** Format: int64 */
            id?: number;
            username?: string;
            name?: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER";
        };
        LoginResponse: {
            accessToken?: string;
            user?: components["schemas"]["AuthUserResponse"];
        };
        DashboardSummaryResponse: {
            /** Format: int64 */
            inProgressTaskCount?: number;
            /** Format: int64 */
            availableWorkerCount?: number;
            /** Format: int64 */
            safetyViolationCount?: number;
            /** Format: int64 */
            pendingInboundCount?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createWorkerAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkerAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateWorkerAccountResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DashboardSummaryResponse"];
                };
            };
        };
    };
}
